//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_mebeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gotovaya_prodykcia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gotovaya_prodykcia()
        {
            this.Sclad = new HashSet<Sclad>();
            this.Tovarnaya_nakladnaya = new HashSet<Tovarnaya_nakladnaya>();
        }
    
        public int ID { get; set; }
        public string Ves { get; set; }
        public string Dlinna { get; set; }
        public string Shirina { get; set; }
        public string Obshivka { get; set; }
        public string Nazvanie { get; set; }
        public string Glubina { get; set; }
        public string Visota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sclad> Sclad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tovarnaya_nakladnaya> Tovarnaya_nakladnaya { get; set; }
    }
}
