//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_mebeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiali()
        {
            this.Postavka = new HashSet<Postavka>();
            this.Sclad = new HashSet<Sclad>();
        }
    
        public int ID { get; set; }
        public string Massiv_drevisini { get; set; }
        public string Pliti_drevestno_sryjechnie { get; set; }
        public string MDF { get; set; }
        public string DVP { get; set; }
        public string Oblicovanniy_shpon { get; set; }
        public string Metall { get; set; }
        public string Raspolozenie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavka> Postavka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sclad> Sclad { get; set; }
    }
}
