//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_mebeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavchik1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavchik1()
        {
            this.Postavka = new HashSet<Postavka>();
            this.Sclad = new HashSet<Sclad>();
        }
    
        public int ID { get; set; }
        public string Telefon { get; set; }
        public string Raspolozenie { get; set; }
        public string Familia_fiz_kica { get; set; }
        public string Ima_fiz_lica { get; set; }
        public string Otchestvo_fiz_lica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavka> Postavka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sclad> Sclad { get; set; }
    }
}
