//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_mebeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sclad
    {
        public int ID { get; set; }
        public Nullable<int> ID_sotrydnika { get; set; }
        public Nullable<int> ID_postavchika { get; set; }
        public Nullable<int> ID_materiala { get; set; }
        public Nullable<int> ID_gotovoy_prodykcii { get; set; }
        public string Raspolozenie { get; set; }
        public string Telefon { get; set; }
    
        public virtual Gotovaya_prodykcia Gotovaya_prodykcia { get; set; }
        public virtual Materiali Materiali { get; set; }
        public virtual Postavchik1 Postavchik1 { get; set; }
        public virtual Sotrydniki Sotrydniki { get; set; }
    }
}
