//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_mebeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovarnaya_nakladnaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovarnaya_nakladnaya()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID { get; set; }
        public string Data { get; set; }
        public Nullable<int> ID_gotovoy_prodykcii { get; set; }
        public string Proizvoditel { get; set; }
        public Nullable<int> ID_zakaza { get; set; }
    
        public virtual Gotovaya_prodykcia Gotovaya_prodykcia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
