//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_mebeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ID { get; set; }
        public string Data { get; set; }
        public Nullable<int> ID_tovarnoy_nakladnoy { get; set; }
    
        public virtual Tovarnaya_nakladnaya Tovarnaya_nakladnaya { get; set; }
    }
}
